# Server
markdown:         rdiscount
pygments:         true
destination:      ./_gh_pages
exclude:          [".idea", ".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE",
                  "Gruntfile.js", "package.json", "node_modules", "README.md", "dist", "less", "metro",
                  "tests", "raw-files.js", "validation-report.json", "validation-status.json"]
host:             0.0.0.0
port:             4000
baseurl:          ""

# Custom vars
current_version:  0.0.1

ghauthor:         "joshkurz"
ghproject:        "open-sesame"
ghname:           "Open Sesame Locksmith"
description:      "321 Open Sesame is the Atlanta Locksmith that truly cares about its customers. Whether you need residential, commercial, or automotive locksmith services. Open Sesame will take care of any locksmith need you may have. Call us today for honest upfront pricing and help."
locale:           "en"
ga-acc:           "" # your Google Analytics tracking No., e.g.  UA-123456789-1

defaults:
  -
    scope:
      path:       ""
    values:
      layout:     "standard"
